// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListProjectParams creates a new ListProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListProjectParams() *ListProjectParams {
	return &ListProjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListProjectParamsWithTimeout creates a new ListProjectParams object
// with the ability to set a timeout on a request.
func NewListProjectParamsWithTimeout(timeout time.Duration) *ListProjectParams {
	return &ListProjectParams{
		timeout: timeout,
	}
}

// NewListProjectParamsWithContext creates a new ListProjectParams object
// with the ability to set a context for a request.
func NewListProjectParamsWithContext(ctx context.Context) *ListProjectParams {
	return &ListProjectParams{
		Context: ctx,
	}
}

// NewListProjectParamsWithHTTPClient creates a new ListProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewListProjectParamsWithHTTPClient(client *http.Client) *ListProjectParams {
	return &ListProjectParams{
		HTTPClient: client,
	}
}

/* ListProjectParams contains all the parameters to send to the API endpoint
   for the list project operation.

   Typically these are written to a http.Request.
*/
type ListProjectParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProjectParams) WithDefaults() *ListProjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list project params
func (o *ListProjectParams) WithTimeout(timeout time.Duration) *ListProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list project params
func (o *ListProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list project params
func (o *ListProjectParams) WithContext(ctx context.Context) *ListProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list project params
func (o *ListProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list project params
func (o *ListProjectParams) WithHTTPClient(client *http.Client) *ListProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list project params
func (o *ListProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
