// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/onepaas/onepaas/pkg/api/v1"
)

// ListProjectReader is a Reader for the ListProject structure.
type ListProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListProjectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListProjectOK creates a ListProjectOK with default headers values
func NewListProjectOK() *ListProjectOK {
	return &ListProjectOK{}
}

/* ListProjectOK describes a response with status code 200, with default header values.

OK
*/
type ListProjectOK struct {
	Payload *models.ProjectList
}

func (o *ListProjectOK) Error() string {
	return fmt.Sprintf("[GET /v1/projects][%d] listProjectOK  %+v", 200, o.Payload)
}
func (o *ListProjectOK) GetPayload() *models.ProjectList {
	return o.Payload
}

func (o *ListProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProjectInternalServerError creates a ListProjectInternalServerError with default headers values
func NewListProjectInternalServerError() *ListProjectInternalServerError {
	return &ListProjectInternalServerError{}
}

/* ListProjectInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListProjectInternalServerError struct {
	Payload *models.Problem
}

func (o *ListProjectInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/projects][%d] listProjectInternalServerError  %+v", 500, o.Payload)
}
func (o *ListProjectInternalServerError) GetPayload() *models.Problem {
	return o.Payload
}

func (o *ListProjectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
